# -*- coding: utf-8 -*-
"""FlowersWhiteBox.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18n-G1PndNhxD7JfN5QiJlCjXZW0bJEvF
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

path= "/content/Iris.csv"
iris = pd.read_csv(path)
iris.head()

iris["Species"].value_counts()

sns.FacetGrid(iris, hue="Species", height=6).map(plt.scatter, "PetalLengthCm", "SepalWidthCm").add_legend()

print(iris["Species"].unique())

flower_mapping = {"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}
iris["Species"] = iris["Species"].map(flower_mapping)
iris.head()
print(iris["Species"].unique())

x = iris[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]].values
y = iris[["Species"]].values

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x,y)

expected = y
predicted = model.predict(x)
predicted

from sklearn import metrics
print(metrics.classification_report(expected, predicted))

print(metrics.confusion_matrix(expected, predicted))